/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdversarialRouteImport } from './routes/adversarial'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as ProofsRouteImport } from './routes/proofs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdversarialRoute = AdversarialRouteImport.update({
  id: '/adversarial',
  path: '/adversarial',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofsRoute = ProofsRouteImport.update({
  id: '/proofs',
  path: '/proofs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adversarial': typeof AdversarialRoute
  '/certificate': typeof CertificateRoute
  '/engine': typeof EngineRoute
  '/ledger': typeof LedgerRoute
  '/proofs': typeof ProofsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adversarial': typeof AdversarialRoute
  '/certificate': typeof CertificateRoute
  '/engine': typeof EngineRoute
  '/ledger': typeof LedgerRoute
  '/proofs': typeof ProofsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adversarial': typeof AdversarialRoute
  '/certificate': typeof CertificateRoute
  '/engine': typeof EngineRoute
  '/ledger': typeof LedgerRoute
  '/proofs': typeof ProofsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/adversarial' | '/certificate' | '/engine' | '/ledger' | '/proofs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adversarial' | '/certificate' | '/engine' | '/ledger' | '/proofs'
  id:
    | '__root__'
    | '/'
    | '/adversarial'
    | '/certificate'
    | '/engine'
    | '/ledger'
    | '/proofs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdversarialRoute: typeof AdversarialRoute
  CertificateRoute: typeof CertificateRoute
  EngineRoute: typeof EngineRoute
  LedgerRoute: typeof LedgerRoute
  ProofsRoute: typeof ProofsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adversarial': {
      id: '/adversarial'
      path: '/adversarial'
      fullPath: '/adversarial'
      preLoaderRoute: typeof AdversarialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proofs': {
      id: '/proofs'
      path: '/proofs'
      fullPath: '/proofs'
      preLoaderRoute: typeof ProofsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdversarialRoute: AdversarialRoute,
  CertificateRoute: CertificateRoute,
  EngineRoute: EngineRoute,
  LedgerRoute: LedgerRoute,
  ProofsRoute: ProofsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
